### ISSUE TITLE
设置签名API失败。

### ISSUE THREAD

**Issue by MildewD** [bling-yshs/HYZL#10]
![PixPin_2024-06-07_15-50-30](https://github.com/bling-yshs/HYZL/assets/120277981/3f4d465e-fe06-4830-861e-6f1136957ab4)

**Comment by bling-yshs** [comment]
emmmm，没启动过一次导致的，我想想应该怎么改

**Comment by bling-yshs** [comment]
> emmmm，没启动过一次导致的，我想想应该怎么改

加个提示吧，毕竟不初始化我不好改
