### ISSUE TITLE
下载device.js失败

### ISSUE THREAD

**Issue by devil233-ui** [bling-yshs/HYZL#11]
![image](https://github.com/user-attachments/assets/56625e0e-4bb0-45c0-acf1-ec62e805a68f)
因为hlhs炸了想换一个
![8864a4d6219e3f867a241eda2c155727](https://github.com/user-attachments/assets/a891de67-8103-46c8-80e2-861ca90ea486)

**Comment by bling-yshs** [comment]
你更新一下启动器试试？我记得我已经修过这个问题了，0.2.67 版本修的

**Comment by devil233-ui** [comment]
抱歉我的问题，虽然更新了，不过桌面快捷方式链的还是老的那个....~~有考虑更新完删掉旧的么~~

**Comment by bling-yshs** [comment]
> 抱歉我的问题，虽然更新了，不过桌面快捷方式链的还是老的那个....~有考虑更新完删掉旧的么~

理论上是会删掉旧的的...除非你多开了导致没法删除，或者是版本太老，可能旧版没有？总之反正现在新的版本我试着是可以的

**Comment by devil233-ui** [comment]
> > 抱歉我的问题，虽然更新了，不过桌面快捷方式链的还是老的那个....~有考虑更新完删掉旧的么~
> 
> 理论上是会删掉旧的的...除非你多开了导致没法删除，或者是版本太老，可能旧版没有？总之反正现在新的版本我试着是可以的

看来是我多开了……这就删
![image](https://github.com/user-attachments/assets/cebfd280-a1e8-45fc-b785-a9bed0d065b2)
对的，0.2.67 版本没有device问题了，不过我印象里遇到个bug是如果直接拷贝新版到新的环境下会缺少权限（哪怕是管理运行）。只能拷贝旧的然后重新升级
