### ISSUE TITLE
更新0.2.74之后，启动器打不开

### ISSUE THREAD

**Issue by mjwmjhw** [bling-yshs/HYZL#15]
![FS(U P$IG2W8NJIARC6A)KC](https://github.com/user-attachments/assets/b9ab30a9-c15b-4f8c-892d-ed95b34402da)
昨天更新之后，启动器打不开了

**Comment by bling-yshs** [comment]
忘记发版了，在构建了，你过五分钟试一下新版本能不能用

**Comment by bling-yshs** [comment]
> ![FS(U P$IG2W8NJIARC6A)KC](https://private-user-images.githubusercontent.com/66258399/367792327-b9ab30a9-c15b-4f8c-892d-ed95b34402da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTY0NDksIm5iZiI6MTcyNjQ5NjE0OSwicGF0aCI6Ii82NjI1ODM5OS8zNjc3OTIzMjctYjlhYjMwYTktYzE1Yi00ZjhjLTg5MmQtZWQ5NWIzNDQwMmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE0MTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNzgyZWFjODI2Yjc1OGRmYjA1MTllYTYwMGI0ODRhNjk4NTZlMWRhYWQzYWM3MjQ2ZGIxNmY2MGYzODMyM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jPOCAlxMbV1imwe4JGk5Kns-hIOQBbs3UXYsO6xEDd4) 昨天更新之后，启动器打不开了

修了但是忘记发新版了，你过五分钟试一下新版本能不能用
