### ISSUE TITLE
安装云崽依赖报错，无法完成依赖安装。

### ISSUE THREAD

**Issue by 1285408958** [bling-yshs/HYZL#18]
![QQ截图20241029171234](https://github.com/user-attachments/assets/fded33ab-15e1-4472-9de9-cd3a1f0b61ab)

目前已删除官方云崽的下载选项，现自动为您下载喵喵云崽

开始下载喵喵云崽...

正在执行命令：git clone --depth=1 https://gitee.com/yoimiya-kokomi/Miao-Yunzai.git
Cloning into 'Miao-Yunzai'...
remote: Enumerating objects: 567, done.
remote: Counting objects: 100% (567/567), done.
remote: Compressing objects: 100% (541/541), done.
remote: Total 567 (delta 29), reused 382 (delta 10), pack-reused 0Receiving objects:  98% (556/567), 16.70 MiB | 4.14 MiB/s
Receiving objects: 100% (567/567), 20.66 MiB | 4.59 MiB/s, done.
Resolving deltas: 100% (29/29), done.

下载喵喵云崽成功！

开始设置 npm 镜像源...

正在执行命令：npm config set registry https://registry.npmmirror.com

设置 npm 镜像源成功！

开始设置 pnpm 镜像源...

正在执行命令：pnpm config set registry https://registry.npmmirror.com

设置 pnpm 镜像源成功！

开始安装云崽依赖

正在执行命令：pnpm install
 WARN  GET https://registry.npmmirror.com/eslint error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/eslint-config-standard error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/eslint-plugin-import error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/eslint-plugin-n error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/eslint-plugin-promise error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/express error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/express-art-template error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/art-template error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/chalk error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/chokidar error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/icqq error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/image-size error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/inquirer error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/lodash error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/log4js error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/md5 error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/eslint error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/eslint-config-standard error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/eslint-plugin-import error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/eslint-plugin-n error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/eslint-plugin-promise error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/express error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/express-art-template error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/art-template error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/chalk error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/chokidar error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/icqq error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/image-size error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/inquirer error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/lodash error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/log4js error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/md5 error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/eslint-config-standard: Value of "this" must be of type URLSearchParams
 WARN  GET https://registry.npmmirror.com/moment error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/eslint-plugin-import: Value of "this" must be of type URLSearchParams
 WARN  GET https://registry.npmmirror.com/node-fetch error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/eslint-plugin-n: Value of "this" must be of type URLSearchParams
 WARN  GET https://registry.npmmirror.com/node-schedule error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/express-art-template: Value of "this" must be of type URLSearchParams
 WARN  GET https://registry.npmmirror.com/oicq error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/art-template: Value of "this" must be of type URLSearchParams
 WARN  GET https://registry.npmmirror.com/pm2 error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/eslint-plugin-promise: Value of "this" must be of type URLSearchParams
 WARN  GET https://registry.npmmirror.com/puppeteer error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/chokidar: Value of "this" must be of type URLSearchParams
 WARN  GET https://registry.npmmirror.com/redis error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/chalk: Value of "this" must be of type URLSearchParams
 WARN  GET https://registry.npmmirror.com/sequelize error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/express: Value of "this" must be of type URLSearchParams
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/image-size: Value of "this" must be of type URLSearchParams
 WARN  GET https://registry.npmmirror.com/ws error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/icqq: Value of "this" must be of type URLSearchParams
 WARN  GET https://registry.npmmirror.com/yaml error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  deprecated icqq@0.6.10: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/inquirer: Value of "this" must be of type URLSearchParams
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/lodash: Value of "this" must be of type URLSearchParams
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/log4js: Value of "this" must be of type URLSearchParams
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/eslint: Value of "this" must be of type URLSearchParams
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/md5: Value of "this" must be of type URLSearchParams
 WARN  GET https://registry.npmmirror.com/moment error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/node-fetch error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/node-schedule error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/oicq error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/pm2 error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/puppeteer error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/redis error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/sequelize error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/ws error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/yaml error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/moment: Value of "this" must be of type URLSearchParams
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/node-fetch: Value of "this" must be of type URLSearchParams
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/node-schedule: Value of "this" must be of type URLSearchParams
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/oicq: Value of "this" must be of type URLSearchParams
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/redis: Value of "this" must be of type URLSearchParams
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/pm2: Value of "this" must be of type URLSearchParams
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/sequelize: Value of "this" must be of type URLSearchParams
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/puppeteer: Value of "this" must be of type URLSearchParams
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/yaml: Value of "this" must be of type URLSearchParams
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/ws: Value of "this" must be of type URLSearchParams
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for ws@^8.18.0

This error happened while installing a direct dependency of F:\yz3\Yunzai-Bot

The latest release of ws is "8.17.0".

If you need the full list of all 164 published versions run "$ pnpm view ws versions".
Progress: resolved 19, reused 18, downloaded 0, added 0

安装云崽依赖成功！

检测到当前目录下不存在 node_modules/icqq/package.json ，初步判断为您的云崽依赖没有正常安装，请尝试使用 BUG修复->重装依赖，若还是无法解决，请到云崽仓库将安装依赖时的报错截图发 issue 反馈，地址 https://gitee.com/yoimiya-kokomi/Miao-Yunzai/issues
按回车键退出...

重装依赖无效，尝试使用美国节点更新依旧无效。

**Comment by bling-yshs** [comment]
close https://gitee.com/bling_yshs/HYZL/issues/IB0LJO
