### ISSUE TITLE
打开启动器 dial tcp:no such host 报错

### ISSUE THREAD

**Issue by Kaze-maru** [bling-yshs/HYZL#19]
![5511CD749695569FACA61E1E8CFDA96D](https://github.com/user-attachments/assets/51fa718d-eb82-4a48-9cff-ee98f134b5bb)

如图

**Comment by bling-yshs** [comment]
域名过期了，我有空修一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月16日(周一) 上午8:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [bling-yshs/HYZL] 打开启动器 dial tcp:no such host 报错 (Issue #19)




 
5511CD749695569FACA61E1E8CFDA96D.png (view on web)
 
如图

**Comment by bling-yshs** [comment]
已修复，但是需要手动下载一次新版本 https://github.com/bling-yshs/HYZL/commit/070b500e5d25ff08ea978d8686c813b8df69394e
