### ISSUE TITLE
运行后直接就闪退了。

### ISSUE THREAD

**Issue by MildewD** [bling-yshs/HYZL#9]
![PixPin_2024-06-07_13-17-45](https://github.com/bling-yshs/HYZL/assets/120277981/47ce3111-50bf-44d8-9043-668990300aef)

**Comment by bling-yshs** [comment]
ok，在修了，谢谢你！

**Comment by MildewD** [comment]
应该是我谢谢你，之前旧的那个启动器一直在用，太好用了。

**Comment by bling-yshs** [comment]
已修 https://github.com/bling-yshs/HYZL/releases/tag/v0.2.58
